repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black --line-length 79
    language: system
    types: [python]
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    types: [python]
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]