# Fetching the latest node image on alpine linux
FROM node:alpine

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./ui/package.json /react-app
RUN npm install

# Copying all the files in our project
COPY ./ui .

# Starting our application
CMD npm start