FROM python:3.11-slim-buster as runtime

# Install dependencies for lammp
RUN apt-get update && apt-get -y install cmake protobuf-compiler && apt-get install -y wget && apt-get install -y build-essential
RUN wget "https://download.lammps.org/tars/lammps-stable.tar.gz"
RUN tar -xvzf lammps-stable.tar.gz
RUN mkdir lammps-2Aug2023/build
WORKDIR lammps-2Aug2023/build

# cmake lammp
RUN cmake ../cmake -D BUILD_SHARED_LIBS=yes -D PKG_MANYBODY=on -D PKG_COLLOID=on
RUN cmake --build .